### ISSUE TITLE
Unable to use Deep concolic with custom cnn model

### ISSUE THREAD

**Issue by lalitkpal** [TrustAI/DeepConcolic#30] opened 2020-12-15 18:41 UTC
Hi,
I have trained a simple CNN and trying to generate test data using Deep concolic but when in run deepconcolic.py on my cnn model, all the layers are recognized as not testable.
Following is abstract form command line window:
<pre>Model: &quot;sequential_1&quot;
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
=================================================================
conv2d (Conv2D)              (None, 90, 110, 32)       896       
_________________________________________________________________
activation (Activation)      (None, 90, 110, 32)       0         
_________________________________________________________________
max_pooling2d (MaxPooling2D) (None, 45, 55, 32)        0         
_________________________________________________________________
conv2d_1 (Conv2D)            (None, 43, 53, 32)        9248      
_________________________________________________________________
activation_1 (Activation)    (None, 43, 53, 32)        0         
_________________________________________________________________
max_pooling2d_1 (MaxPooling2 (None, 21, 26, 32)        0         
_________________________________________________________________
flatten (Flatten)            (None, 17472)             0         
_________________________________________________________________
dense (Dense)                (None, 64)                1118272   
_________________________________________________________________
activation_2 (Activation)    (None, 64)                0         
_________________________________________________________________
dense_1 (Dense)              (None, 40)                2600      
_________________________________________________________________
activation_3 (Activation)    (None, 40)                0         
=================================================================
Total params: 1,131,016
Trainable params: 1,131,016
Non-trainable params: 0
_________________________________________________________________
Loading input data from data/attdata... data/attdata
data/attdata
</pre>
...
<pre>400 loaded.
DNN under test has 11 layer functions, 0 of which is to be covered:
[]

Starting tests for criterion NC with norm L0.                                   
Outputs will go into: attout/
Reporting into: attout/NC_L0-2020-12-16-00-04-03.445382_report.txt              
Randomly selecting an input from test data.                                     
#0 NC: 0.00000000%   </pre>

Please suggest how to resolve this issue.

Thanks,
Lalit Kumar

**Comment by xiaoweih** [comment] 2020-12-16 09:06
Hi Lalit, I think this may relate to how you connect the the software with your model. It is difficult to see what the problem is by the little information you gave us. If possible, please let us know a bit more on your program.

**Comment by lalitkpal** [comment] 2020-12-17 08:03
Hi Xiaowei,
I have attached program file and trained model file for your reference. Please let me know if need more information.

[CNN_FeceRec.zip](https://github.com/TrustAI/DeepConcolic/files/5707794/CNN_FeceRec.zip)
[facerec_cnn.h5.zip](https://github.com/TrustAI/DeepConcolic/files/5707800/facerec_cnn.h5.zip)

**Comment by xiaoweih** [comment] 2021-05-10 20:48
Please check to see if that works for you: 

https://github.com/TrustAI/DeepConcolic#working-with-your-own-datasets

**Comment by xiaoweih** [comment] 2021-07-18 09:45
It has been two months since the last communication of this thread. I will therefore close this session.

**Closed as completed** 2021-07-18 09:44 UTC
